eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: words-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: words-article
words: a,the

---
spring:
  profiles: words-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noum
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: words-noum
words: boat,book,vote,seat,backpack,partition,groundhog  
